---
probableCause:
  '0': m3100Indeterminate
  '1': m3100AlarmIndicationSignal
  '2': m3100CallSetupFailure
  '3': m3100DegradedSignal
  '4': m3100FarEndReceiverFailure
  '5': m3100FramingError
  '6': m3100LossOfFrame
  '7': m3100LossOfPointer
  '8': m3100LossOfSignal
  '9': m3100PayloadTypeMismatch
  '10': m3100TransmissionError
  '11': m3100RemoteAlarmInterface
  '12': m3100ExcessiveBitErrorRate
  '13': m3100PathTraceMismatch
  '14': m3100Unavailable
  '15': m3100SignalLabelMismatch
  '16': m3100LossOfMultiFrame
  '17': receiveFailure
  '18': transmitFailure
  '19': modulationFailure
  '20': demodulationFailure
  '21': broadcastChannelFailure
  '22': connectionEstablishmentError
  '23': invalidMessageReceived
  '24': localNodeTransmissionError
  '25': remoteNodeTransmissionError
  '26': routingFailure
  '51': m3100BackPlaneFailure
  '52': m3100DataSetProblem
  '53': m3100EquipmentIdentifierDuplication
  '54': m3100ExternalIfDeviceProblem
  '55': m3100LineCardProblem
  '56': m3100MultiplexerProblem
  '57': m3100NeIdentifierDuplication
  '58': m3100PowerProblem
  '59': m3100ProcessorProblem
  '60': m3100ProtectionPathFailure
  '61': m3100ReceiverFailure
  '62': m3100ReplaceableUnitMissing
  '63': m3100ReplaceableUnitTypeMismatch
  '64': m3100SynchronisationSourceMismatch
  '65': m3100TerminalProblem
  '66': m3100TimingProblem
  '67': m3100TransmitterFailure
  '68': m3100TrunkCardProblem
  '69': m3100ReplaceableUnitProblem
  '70': realTimeClockFailure
  '71': antennaFailure
  '72': batteryChargingFailure
  '73': diskFailure
  '74': frequencyHoppingFailure
  '75': iODeviceError
  '76': lossOfSynchronisation
  '77': lossOfRedundancy
  '78': powerSupplyFailure
  '79': signalQualityEvaluationFailure
  '80': tranceiverFailure
  '81': protectionMechanismFailure
  '82': protectingResourceFailure
  '101': m3100AirCompressorFailure
  '102': m3100AirConditioningFailure
  '103': m3100AirDryerFailure
  '104': m3100BatteryDischarging
  '105': m3100BatteryFailure
  '106': m3100CommercialPowerFailure
  '107': m3100CoolingFanFailure
  '108': m3100EngineFailure
  '109': m3100FireDetectorFailure
  '110': m3100FuseFailure
  '111': m3100GeneratorFailure
  '112': m3100LowBatteryThreshold
  '113': m3100PumpFailure
  '114': m3100RectifierFailure
  '115': m3100RectifierHighVoltage
  '116': m3100RectifierLowVoltage
  '117': m3100VentilationSystemFailure
  '118': m3100EnclosureDoorOpen
  '119': m3100ExplosiveGas
  '120': m3100Fire
  '121': m3100Flood
  '122': m3100HighHumidity
  '123': m3100HighTemperature
  '124': m3100HighWind
  '125': m3100IceBuildUp
  '127': m3100LowFuel
  '128': m3100LowHumidity
  '129': m3100LowCablePressure
  '130': m3100LowTemperature
  '131': m3100LowWater
  '132': m3100Smoke
  '133': m3100ToxicGas
  '134': m3100CoolingSystemFailure
  '135': m3100ExternalEquipmentFailure
  '136': m3100ExternalPointFailure
  '151': m3100StorageCapacityProblem
  '152': m3100MemoryMismatch
  '153': m3100CorruptData
  '154': m3100OutOfCPUCycles
  '155': m3100SoftwareEnvironmentProblem
  '156': m3100SoftwareDownloadFailure
  '157': m3100LossOfRealTimel
  '158': applicationSubsystemFailure
  '159': configurationOrCustomisationError
  '160': databaseInconsistency
  '161': fileError
  '162': outOfMemory
  '163': softwareError
  '164': timeoutExpired
  '165': underlayingResourceUnavailable
  '166': versionMismatch
  '201': bandwidthReduced
  '202': congestion
  '203': excessiveErrorRate
  '204': excessiveResponseTime
  '205': excessiveRetransmissionRate
  '206': reducedLoggingCapability
  '207': systemResourcesOverload
  '301': x733AdapterError
  '302': x733ApplicationSubsystemFailure
  '303': x733BandwidthReduced
  '305': x733CommunicationsProtocolError
  '306': x733CommunicationsSubsystemFailure
  '307': x733ConfigurationOrCustomizationError
  '308': x733Congestion
  '310': x733CpuCyclesLimitExceeded
  '311': x733DataSetOrModemError
  '313': x733DTEDCEInterfaceError
  '315': x733EquipmentMalfunction
  '316': x733ExcessiveVibration
  '317': x733FileError
  '321': x733HeatingOrVentilationOrCoolingSystemProblem
  '322': x733HumidityUnacceptable
  '323': x733InputOutputDeviceError
  '324': x733InputDeviceError
  '325': x733LANError
  '326': x733LeakDetected
  '327': x733LocalNodeTransmissionError
  '330': x733MaterialSupplyExhausted
  '332': x733OutOfMemory
  '333': x733OuputDeviceError
  '334': x733PerformanceDegraded
  '336': x733PressureUnacceptable
  '339': x733QueueSizeExceeded
  '340': x733ReceiveFailure
  '342': x733RemoteNodeTransmissionError
  '343': x733ResourceAtOrNearingCapacity
  '344': x733ResponseTimeExcessive
  '345': x733RetransmissionRateExcessive
  '346': x733SoftwareError
  '347': x733SoftwareProgramAbnormallyTerminated
  '348': x733SoftwareProgramError
  '350': x733TemperatureUnacceptable
  '351': x733ThresholdCrossed
  '353': x733ToxicLeakDetected
  '354': x733TransmitFailure
  '356': x733UnderlyingResourceUnavailable
  '357': x733VersionMismatch
  '401': x736AuthenticationFailure
  '402': x736BreachOfConfidentiality
  '403': x736CableTamper
  '404': x736DelayedInformation
  '405': x736DenialOfService
  '406': x736DuplicateInformation
  '407': x736InformationMissing
  '408': x736InformationModificationDetected
  '409': x736InformationOutOfSequence
  '410': x736IntrusionDetection
  '411': x736KeyExpired
  '412': x736NonRepudiationFailure
  '413': x736OutOfHoursActivity
  '414': x736OutOfService
  '415': x736ProceduralError
  '416': x736UnauthorizedAccessAttempt
  '417': x736UnexpectedInformation
  '418': x736UnspecifiedReason
  '501': gsm1211AbisToBTSInterfaceFailure
  '502': gsm1211AbisToTRXInterfaceFailure
  '503': gsm1211AntennaProblem
  '504': gsm1211BatteryBreakdown
  '505': gsm1211BatteryChargingFault
  '506': gsm1211ClockSynchronisationProblem
  '507': gsm1211CombinerProblem
  '508': gsm1211DiskProblem
  '510': gsm1211ExcessiveReceiverTemperature
  '511': gsm1211ExcessiveTransmitterOutputPower
  '512': gsm1211ExcessiveTransmitterTemperature
  '513': gsm1211FrequencyHoppingDegraded
  '514': gsm1211FrequencyHoppingFailure
  '515': gsm1211FrequencyRedefinitionFailed
  '516': gsm1211LineInterfaceFailure
  '517': gsm1211LinkFailure
  '518': gsm1211LossOfSynchronisation
  '519': gsm1211LostRedundancy
  '520': gsm1211MainsBreakdownWithBatteryBackUp
  '521': gsm1211MainsBreakdownWithoutBatteryBackUp
  '522': gsm1211PowerSupplyFailure
  '523': gsm1211ReceiverAntennaFault
  '525': gsm1211ReceiverMulticouplerFailure
  '526': gsm1211ReducedTransmitterOutputPower
  '527': gsm1211SignalQualityEvaluationFault
  '528': gsm1211TimeslotHardwareFailure
  '529': gsm1211TransceiverProblem
  '530': gsm1211TranscoderProblem
  '531': gsm1211TranscoderOrRateAdapterProblem
  '532': gsm1211TransmitterAntennaFailure
  '533': gsm1211TransmitterAntennaNotAdjusted
  '535': gsm1211TransmitterLowVoltageOrCurrent
  '536': gsm1211TransmitterOffFrequency
  '537': gsm1211DatabaseInconsistency
  '538': gsm1211FileSystemCallUnsuccessful
  '539': gsm1211InputParameterOutOfRange
  '540': gsm1211InvalidParameter
  '541': gsm1211InvalidPointer
  '542': gsm1211MessageNotExpected
  '543': gsm1211MessageNotInitialised
  '544': gsm1211MessageOutOfSequence
  '545': gsm1211SystemCallUnsuccessful
  '546': gsm1211TimeoutExpired
  '547': gsm1211VariableOutOfRange
  '548': gsm1211WatchDogTimerExpired
  '549': gsm1211CoolingSystemFailure
  '550': gsm1211ExternalEquipmentFailure
  '551': gsm1211ExternalPowerSupplyFailure
  '552': gsm1211ExternalTransmissionDeviceFailure
  '561': gsm1211ReducedAlarmReporting
  '562': gsm1211ReducedEventReporting
  '563': gsm1211ReducedLoggingCapability
  '564': gsm1211SystemResourcesOverload
  '565': gsm1211BroadcastChannelFailure
  '566': gsm1211ConnectionEstablishmentError
  '567': gsm1211InvalidMessageReceived
  '568': gsm1211InvalidMSUReceived
  '569': gsm1211LAPDLinkProtocolFailure
  '570': gsm1211LocalAlarmIndication
  '571': gsm1211RemoteAlarmIndication
  '572': gsm1211RoutingFailure
  '573': gsm1211SS7ProtocolFailure
  '574': gsm1211TransmissionError
  '600': i610LocEndToEnd
  '601': i610AisEndToEnd
  '602': i610RdiEndToEnd
  '603': i610LocSegmentLinkSide
  '604': i610LocSegmentCoreSide
  '605': i610AisSegmentLinkSide
  '606': i610AisSegmentCoreSide
  '607': i610RdiSegmentLinkSide
  '608': i610RdiSegmentCoreSide
  '1600': authenticationFailure
  '1601': breachOfConfidentiality
  '1602': cableTamper
  '1603': delayedInformation
  '1604': denialOfService
  '1605': duplicateInformation
  '1606': informationMissing
  '1607': informationModificationDetected
  '1608': informationOutOfSequence
  '1609': keyExpired
  '1610': nonRepudiationFailure
  '1611': outOfHoursActivity
  '1612': outOfService
  '1613': proceduralError
  '1614': unauthorizedAccessAttempt
  '1615': unexpectedInformation
  '100500': adapterError
  '100501': applicationSubsystemFailture
  '100502': bandwidthReducedX733
  '100503': callEstablishmentError
  '100504': communicationsProtocolError
  '100505': communicationsSubsystemFailure
  '100506': configurationOrCustomizationError
  '100507': congestionX733
  '100508': coruptData
  '100509': cpuCyclesLimitExceeded
  '100510': dataSetOrModemError
  '100511': degradedSignalX733
  '100512': dteDceInterfaceError
  '100513': enclosureDoorOpenX733
  '100514': equipmentMalfunction
  '100515': excessiveVibration
  '100516': fileErrorX733
  '100517': fireDetected
  '100518': framingErrorX733
  '100519': heatingVentCoolingSystemProblem
  '100520': humidityUnacceptable
  '100521': inputOutputDeviceError
  '100522': inputDeviceError
  '100523': lanError
  '100524': leakDetected
  '100525': localNodeTransmissionErrorX733
  '100526': lossOfFrameX733
  '100527': lossOfSignalX733
  '100528': materialSupplyExhausted
  '100529': multiplexerProblemX733
  '100530': outOfMemoryX733
  '100531': ouputDeviceError
  '100532': performanceDegraded
  '100533': powerProblems
  '100534': pressureUnacceptable
  '100535': processorProblems
  '100536': pumpFailureX733
  '100537': queueSizeExceeded
  '100538': receiveFailureX733
  '100539': receiverFailureX733
  '100540': remoteNodeTransmissionErrorX733
  '100541': resourceAtOrNearingCapacity
  '100542': responseTimeExecessive
  '100543': retransmissionRateExcessive
  '100544': softwareErrorX733
  '100545': softwareProgramAbnormallyTerminated
  '100546': softwareProgramError
  '100547': storageCapacityProblemX733
  '100548': temperatureUnacceptable
  '100549': thresholdCrossed
  '100550': timingProblemX733
  '100551': toxicLeakDetected
  '100552': transmitFailureX733
  '100553': transmiterFailure
  '100554': underlyingResourceUnavailable
  '100555': versionMismatchX733
  '1001': lossOfTimingSource
  '1002': apsChannelProcessingFailure
  '1003': apsByteFailure
  '1004': apsChannelMatchFailure
  '1005': apsModeMismatch
  '1007': lossOfTUMultiframeIndicator
  '1010': pathSelectorFailure
  '1011': blsrDefaultKBytes
  '1012': blsrInconsistentAPSCodes
  '1013': blsrNodeIdMismatch
  '1014': blsrImproperAPSCodes
  '1015': blsrSquelching
  '1016': blsrInvalidNeighbour
  '1017': blsrInvalidRingMap
  '1018': blsrInvalidRingId
  '1019': blsrIncompleteRingConfig
  '1020': blsrIncompleteETConfig
  '1021': blsrNodeIncorrectOrientation
  '1022': hwResourceExhaused
  '1023': hwResourceThreshold
  '1024': other
  '1025': pwOutage
